function [ax,hlines] = plotyyy(x1,y1,x2,y2,x3,y3,x4,y4,ylabels,time)
%PLOTYYY - Extends plotyy to include a third y-axis
%
%Syntax:  [ax,hlines] = plotyyy(x1,y1,x2,y2,x3,y3,ylabels)
%
%Inputs: x1,y1 are the xdata and ydata for the first axes' line
%        x2,y2 are the xdata and ydata for the second axes' line
%        x3,y3 are the xdata and ydata for the third axes' line
%        ylabels is a 3x1 cell array containing the ylabel strings
%
%Outputs: ax -     3x1 double array containing the axes' handles
%         hlines - 3x1 double array containing the lines' handles
%
%Example:
%x=0:10; 
%y1=x;  y2=x.^2;   y3=x.^3;
%ylabels{1}='First y-label';
%ylabels{2}='Second y-label';
%ylabels{3}='Third y-label';
%[ax,hlines] = plotyyy(x,y1,x,y2,x,y3,ylabels);
%legend(hlines, 'y = x','y = x^2','y = x^3',2)
%
%m-files required: none
%Author: Denis Gilbert, Ph.D., physical oceanography
%Maurice Lamontagne Institute
%Dept. of Fisheries and Oceans Canada
%email: gilbertd@dfo-mpo.gc.ca  
%Web: http://www.qc.dfo-mpo.gc.ca/iml/
%April 2000; Last revision: 14-Nov-2001
if nargin==6
   %Use empty strings for the ylabels
   ylabels{1}=' '; ylabels{2}=' '; ylabels{3}=' '; ylabels{4}=' ';
elseif nargin > 7
%    display('Too many input arguments')
elseif nargin < 6
   error('Not enough input arguments')
end
% figure('units','normalized',...
%        'DefaultAxesXMinorTick','on','DefaultAxesYminorTick','on'); 
%Plot the first two lines with plotyy
[ax,hlines(1),hlines(2)] = plotyy(x1,y1,x2,y2);
cfig = get(gcf,'color');
title('Logged Data')
pos = [0.0525 0.065  1.075  0.5125]; %[left bottom width height]
% pos = get(gca,'pos');
offset = pos(3)/5.5;
%Reduce width of the two axes generated by plotyy 
% pos(3) = pos(3) - offset/2;
pos(3) = pos(3) - offset;
set(ax,'position',pos);
set(ax(1),'YLim',[-10000 15000], 'YColor',[0.67843      0.42353      0.29412])
set(ax(2),'YLim',[-10000 15000])
set(ax(1),'YTick',[2000:2000:14000])
xlabel('Time');
yt=get(gca,'YTick');
set(gca,'YTickLabel',sprintf('%1.0f\n',yt))
format shortG
% set(ax(2),'YTick',[0:1000:15000])
set(ax(2), 'Visible','off')
set(hlines(1),'LineWidth',2);
set(hlines(1),'Color',[0      0 0.7])
set(hlines(2),'Color',[0.74118      0.05098      0.17647])
set(hlines(2),'LineWidth',6); %RPM Pass-Through
set(gca,'Color','k')
hold on
yline(2000,':','LineWidth',0.625,'Color',[1 0.8 .7]);
yline(4000,':','LineWidth',0.625,'Color',[1 0.8 .7]);
yline(6000,':','LineWidth',0.625,'Color',[1 0.8 0.7]);
yline(8000,':','LineWidth',0.625,'Color',[1 0.8 0.7]);
yline(10000,':','LineWidth',0.625,'Color',[1 0.8 0.7]);
yline(12000,':','LineWidth',0.625,'Color',[1 0.8 0.7]);
yline(14000,':','LineWidth',0.625,'Color',[1 0.8 0.7]);
%Determine the position of the third axes
% pos3=[pos(1) pos(2) pos(3)+offset pos(4)];
pos3=[pos(1) pos(2) pos(3) pos(4)];
%Determine the proper x-limits for the third axes
limx1=get(ax(1),'xlim');
limx3=[limx1(1)   limx1(1) + 1*(limx1(2)-limx1(1))];
%Bug fix 14 Nov-2001: the 1.2 scale factor in the line above
%was contributed by Mariano Garcia (BorgWarner Morse TEC Inc)
ax(3)=axes('Position',pos3,'box','off',...
   'Color','none','XColor','k','YColor',[0 0.5 0],...   
   'xtick',[],'xlim',limx3,'yaxislocation','right');
ax(4)=axes('Position',pos3,'box','off',...
   'Color','none','XColor','k','YColor','r',...   
   'xtick',[],'xlim',limx3,'yaxislocation','right');
hlines(3) = line(x3,y3,'Color',[0.5 0.18 0.56],'Parent',ax(3));
set(hlines(3),'LineWidth',2);
% display(hlines(3));
hlines(4) = line(x4,y4,'Color','y','Parent',ax(4));
set(hlines(4),'LineWidth',5); % TP Pass-Through
% limy3=get(ax(3),'YLim');
limy3 = [-100 500];
set(ax(3),'YLim',[0 200]);
set(ax(4),'YLim',[0 200]);
% set(ax(3),'YTick',[0:20:100],'Ycolor', 'white', 'gridlinestyle','-','ygrid','on', 'LineWidth', 2);
set(ax(3),'YTick',[0:20:100])
set(ax(4), 'Visible','off');
hold on
%y-grid
yline(20,':','LineWidth',1,'Color',[0 0.5 0]);
yline(40,':','LineWidth',1,'Color',[0 0.5 0]);
yline(60,':','LineWidth',1,'Color',[0 0.5 0]);
yline(80,':','LineWidth',1,'Color',[0 0.5 0]);
yline(100,':','LineWidth',1,'Color',[0 0.5 0]);
%x-grid
for i = 1:1:24
    xlines = xline(50*i,'--','LineWidth',.5,'Color',[0.6 0.6 0.6]);
end
% plot(0:time,[20,20],'r','LineWidth',5);
%Hide unwanted portion of the x-axis line that lies
%between the end of the second and third axes
line([limx1(2) limx3(2)],[limy3(1) limy3(1)],...
   'Color',cfig,'Parent',ax(3),'Clipping','off');
axes(ax(2));
%Label all three y-axes
set(get(ax(1),'ylabel'),'string',ylabels{1});
% set(get(ax(2),'ylabel'),'string',ylabels{2})
set(get(ax(3),'ylabel'),'string',ylabels{3},'HorizontalAlignment','left','VerticalAlignment','bottom');
set(get(ax(3),'ylabel'),'rotation',270);
% set(get(ax(4),'ylabel'),'string',ylabels{4})
% ax = gca
% ax.SortMethod
% ax.Children
datacursormode on

